/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antcolony_tsp;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author wilfredojose
 */
public class ventanaAbrir extends javax.swing.JFrame {

    private int cantCitiesO = 0;
    private int cantVerticesO = 0;
    public static double[][] matDistances;
    public static String[] nomCities;
    public static int cantCities = 0;
    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    Archivos gestion = new Archivos();
    /**
     * Creates new form ventanaAbrir
     */
    public ventanaAbrir() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnSimular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setDisabledTextColor(new java.awt.Color(102, 102, 255));
        txtArea.setEnabled(false);
        jScrollPane1.setViewportView(txtArea);

        btnSimular.setText("Cargar y simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Nota: Al cargar un archivo\npara simularlo, solo es necesario\ncolocar las constantes, las iteraciones y hormigas,\ny darle a correr!");
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnSimular)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        //parte en la que se obtienen los  datos de un txt
        
        String txtEnLabel = txtArea.getText(); 
                           
        if(txtEnLabel.contains("§")){ //si contiene ese simbolo (ver metodo de convertiratxt en conversionesDeTexto) es porque se puede leer              
            cantCities = conversionesDeTexto.obtenerCiudades(txtEnLabel, cantCitiesO);
            int cantVertices = conversionesDeTexto.obtenerVertices(txtEnLabel, cantVerticesO); 
            double[][] matDistancias = new double[cantCities][cantCities];
            String[] nombresCiudades = new String[cantCities];

            matDistances = (conversionesDeTexto.obtenerMatrizDistancias(txtEnLabel, cantCities, cantVertices, matDistancias));
            nomCities = (conversionesDeTexto.obtenerNombresCiudades(txtEnLabel, nombresCiudades));

            Gráfica grafica = new Gráfica(0);
            grafica.setEsCargado(true);

            grafica.show();
            grafica.getAgregar().setEnabled(false);
            grafica.getBtnFijarGrafo().setEnabled(false);
            grafica.getElimnar().setEnabled(false);
            this.dispose();
        }else{ //si no, te abre los archivos de nuevo
            JOptionPane.showMessageDialog(this, "Archivo no compatible, pruebe de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
            if(seleccionado.showDialog(this, "Abrir archivo")== JFileChooser.APPROVE_OPTION){
                archivo = seleccionado.getSelectedFile();
                if(archivo.canRead()){
                    if(archivo.getName().endsWith("txt")){
                        String contenido = gestion.abrirTexto(archivo);
                        txtArea.setText(contenido);
                    }else{
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo válido", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
//            Gráfica grafica = new Gráfica(0);
//            grafica.show();
//            this.dispose();
        }
    }//GEN-LAST:event_btnSimularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaAbrir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaAbrir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaAbrir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaAbrir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaAbrir().setVisible(true);
            }
        });
    }

    public JTextArea getTxtArea() {
        return txtArea;
    }

    public void setTxtArea(JTextArea txtArea) {
        this.txtArea = txtArea;
    }

    public double[][] getMatDistances() {
        return matDistances;
    }

    public void setMatDistances(double[][] matDistances) {
        this.matDistances = matDistances;
    }

    public String[] getNomCities() {
        return nomCities;
    }

    public void setNomCities(String[] nomCities) {
        this.nomCities = nomCities;
    }
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimular;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
